version: "3"
services:
  lb:
    image: haproxy
    ports:
      - 8080:8080
    depends_on:
      - app1
      - app2
      - app3
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
    networks:
      - awesome-app-network

  app1:
    container_name: app1
    build:
      context: ./main
      dockerfile: Dockerfile
    environment:
      - APPID=1111
    env_file:
      - docker.env
    depends_on:
      - user
      - profile
      - mail
    volumes:
      - ./main:/app
      - /app/node_modules
    networks:
      - awesome-app-network

  app2:
    image: microservices_app1
    environment:
      - APPID=2222
    env_file:
      - docker.env
    volumes:
      - ./main:/app
      - /app/node_modules
    networks:
      - awesome-app-network

  app3:
    image: microservices_app1
    environment:
      - APPID=3333
    env_file:
      - docker.env
    volumes:
      - ./main:/app
      - /app/node_modules
    networks:
      - awesome-app-network

  user:
    container_name: user
    build:
      context: ./user
      dockerfile: Dockerfile
    env_file:
      - docker.env
    depends_on:
      - nats
    volumes:
      - ./user:/app
      - /app/node_modules
    networks:
      - awesome-app-network

  profile:
    container_name: profile
    build:
      context: ./profile
      dockerfile: Dockerfile
    env_file:
      - docker.env
    depends_on:
      - nats
    volumes:
      - ./profile:/app
      - /app/node_modules
    networks:
      - awesome-app-network

  mail:
    container_name: mail
    build:
      context: ./mail
      dockerfile: Dockerfile
    env_file:
      - docker.env
    depends_on:
      - nats
    volumes:
      - ./mail:/app
      - /app/node_modules
    networks:
      - awesome-app-network

  nats:
    container_name: nats
    image: nats:alpine
    networks:
      - awesome-app-network

networks:
  awesome-app-network:
    driver: bridge
